spring:
  application:
    name: screenmatch
  config:
    import: optional:datasource-config.properties
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
omdb-api-key: ${OMDB_API_KEY}
